"""A Python package for analyzing and transforming text."""

import importlib
from typing import Any, TYPE_CHECKING

from textwarp._core.models import POSCounts, WordCount

_MODULE_MAP: dict[str, str] = {
    'calculate_time_to_read': 'textwarp._lib.analysis',
    'calculate_ttr': 'textwarp._lib.analysis',
    'capitalize': 'textwarp._lib.casing',
    'cardinal_to_ordinal': 'textwarp._lib.numbers',
    'count_chars': 'textwarp._lib.analysis',
    'count_entities': 'textwarp._lib.analysis',
    'count_lines': 'textwarp._lib.analysis',
    'count_mfws': 'textwarp._lib.analysis',
    'count_pos': 'textwarp._lib.analysis',
    'count_sents': 'textwarp._lib.analysis',
    'count_words': 'textwarp._lib.analysis',
    'curly_to_straight': 'textwarp._lib.punctuation',
    'expand_contractions': 'textwarp._lib.contractions',
    'from_binary': 'textwarp._lib.encoding',
    'from_hexadecimal': 'textwarp._lib.encoding',
    'from_morse': 'textwarp._lib.encoding',
    'hyphens_to_em': 'textwarp._lib.punctuation',
    'hyphens_to_en': 'textwarp._lib.punctuation',
    'ordinal_to_cardinal': 'textwarp._lib.numbers',
    'punct_to_inside': 'textwarp._lib.punctuation',
    'punct_to_outside': 'textwarp._lib.punctuation',
    'random_case': 'textwarp._lib.effects',
    'randomize': 'textwarp._lib.effects',
    'redact': 'textwarp._lib.effects',
    'reverse': 'textwarp._lib.effects',
    'straight_to_curly': 'textwarp._lib.punctuation',
    'strip_html': 'textwarp._lib.cleaning',
    'to_alternating_caps': 'textwarp._lib.effects',
    'to_binary': 'textwarp._lib.encoding',
    'to_camel_case': 'textwarp._lib.casing',
    'to_dot_case': 'textwarp._lib.casing',
    'to_hexadecimal': 'textwarp._lib.encoding',
    'to_kebab_case': 'textwarp._lib.casing',
    'to_morse': 'textwarp._lib.encoding',
    'to_pascal_case': 'textwarp._lib.casing',
    'to_sentence_case': 'textwarp._lib.casing',
    'to_single_spaces': 'textwarp._lib.cleaning',
    'to_snake_case': 'textwarp._lib.casing',
    'to_title_case': 'textwarp._lib.casing',
    'to_zalgo': 'textwarp._lib.effects',
    'unzalgo': 'textwarp._lib.effects',
    'widen': 'textwarp._lib.effects'
}

__all__ = list(_MODULE_MAP.keys())

if TYPE_CHECKING:
    from spacy.tokens import Doc

    def calculate_time_to_read(text: str, wpm: int) -> int: ...
    def calculate_ttr(content: str | Doc) -> float: ...
    def capitalize(content: str | Doc) -> str: ...
    def cardinal_to_ordinal(text: str) -> str: ...
    def count_chars(text: str) -> int: ...
    def count_entities(
        content: str | Doc, num_entities: int
    ) -> list[WordCount]: ...
    def count_lines(text: str) -> int: ...
    def count_mfws(content: str | Doc, num_mfws: int) -> list[WordCount]: ...
    def count_pos(content: str | Doc) -> POSCounts: ...
    def count_sents(content: str | Doc) -> int: ...
    def count_words(content: str | Doc) -> int: ...
    def curly_to_straight(text: str) -> str: ...
    def expand_contractions(content: str | Doc) -> str: ...
    def from_binary(binary_text: str) -> str: ...
    def from_hexadecimal(text: str) -> str: ...
    def from_morse(text: str) -> str: ...
    def hyphens_to_em(text: str) -> str: ...
    def hyphens_to_en(text: str) -> str: ...
    def ordinal_to_cardinal(text: str) -> str: ...
    def punct_to_inside(text: str) -> str: ...
    def punct_to_outside(text: str) -> str: ...
    def random_case(text: str) -> str: ...
    def randomize(text: str) -> str: ...
    def redact(text: str) -> str: ...
    def reverse(text: str) -> str: ...
    def straight_to_curly(text: str) -> str: ...
    def strip_html(text: str) -> str: ...
    def to_alternating_caps(text: str) -> str: ...
    def to_binary(text: str) -> str: ...
    def to_camel_case(text: str) -> str: ...
    def to_dot_case(text: str) -> str: ...
    def to_hexadecimal(text: str) -> str: ...
    def to_kebab_case(text: str) -> str: ...
    def to_morse(text: str) -> str: ...
    def to_pascal_case(text: str) -> str: ...
    def to_sentence_case(content: str | Doc) -> str: ...
    def to_single_spaces(text: str) -> str: ...
    def to_snake_case(text: str) -> str: ...
    def to_title_case(content: str | Doc) -> str: ...
    def to_zalgo(text: str) -> str: ...
    def unzalgo(text: str) -> str: ...
    def widen(text: str) -> str: ...


def __getattr__(name: str) -> Any:
    """
    Lazily load functions from submodules when accessed as attributes of
    the package.

    Args:
        name: The name of the accessed attribute.

    Raises:
        AttributeError: If the module has no such attribute.
    """
    if name in _MODULE_MAP:
        mod = importlib.import_module(_MODULE_MAP[name])
        val = getattr(mod, name)
        globals()[name] = getattr(mod, name)
        return val

    raise AttributeError(f'module {__name__!r} has no attribute {name!r}')
