[tox]
envlist = py310, py311, py312, py313, py314
isolated_build = true
skip_missing_interpreters = true

[testenv]
extras =
    clipboard
    markdown
    nlp
    test
commands =
python -c "import spacy.util, sys, subprocess; \
        sys.exit(0) if spacy.util.is_package('en_core_web_sm') \
        else subprocess.check_call([sys.executable, '-m', 'spacy', 'download', 'en_core_web_sm'])"
    pytest --cov=textwarp --cov-fail-under=85
