"""A Python package for analyzing and transforming text."""

from ._lib import (
    curly_to_straight,
    straight_to_curly
)
from .analysis import (
    count_chars,
    count_lines,
    count_mfws,
    count_pos,
    calculate_time_to_read
)
from .warping import (
    capitalize,
    cardinal_to_ordinal,
    expand_contractions,
    from_hexadecimal,
    from_morse,
    hyphens_to_em,
    hyphen_to_en,
    ordinal_to_cardinal,
    punct_to_inside,
    punct_to_outside,
    randomize,
    random_case,
    redact,
    reverse,
    to_alternating_caps,
    to_binary,
    to_camel_case,
    to_dot_case,
    to_hexadecimal,
    to_kebab_case,
    to_morse,
    to_pascal_case,
    to_sentence_case,
    to_single_spaces,
    to_snake_case,
    to_title_case,
    widen
)

__all__ = [
    'calculate_time_to_read',
    'capitalize',
    'cardinal_to_ordinal',
    'count_chars',
    'count_lines',
    'count_mfws',
    'count_pos',
    'curly_to_straight',
    'expand_contractions',
    'from_hexadecimal',
    'from_morse',
    'hyphens_to_em',
    'hyphen_to_en',
    'ordinal_to_cardinal',
    'punct_to_inside',
    'punct_to_outside',
    'randomize',
    'random_case',
    'redact',
    'reverse',
    'straight_to_curly',
    'to_alternating_caps',
    'to_binary',
    'to_camel_case',
    'to_dot_case',
    'to_hexadecimal',
    'to_kebab_case',
    'to_morse',
    'to_pascal_case',
    'to_sentence_case',
    'to_single_spaces',
    'to_snake_case',
    'to_title_case',
    'widen'
]
