"""Exposes command-line inputs and messages."""

from textwarp._cli.constants.inputs import (
    get_exit_inputs,
    get_no_inputs,
    get_yes_inputs
)
from textwarp._cli.constants.messages import (
    ANY_OTHER_TEXT_PROMPT,
    CASE_NOT_FOUND_MSG,
    CLIPBOARD_ACCESS_ERROR_MSG,
    CLIPBOARD_CLEARED_MSG,
    ENTER_CASE_TO_REPLACE_PROMPT,
    ENTER_MFW_COUNT_PROMPT,
    ENTER_VALID_NUMBER_PROMPT,
    ENTER_REGEX_PROMPT,
    ENTER_REPLACEMENT_CASE_PROMPT,
    ENTER_REPLACEMENT_TEXT_PROMPT,
    ENTER_TEXT_TO_REPLACE_PROMPT,
    ENTER_VALID_CASE_PROMPT,
    ENTER_VALID_REGEX_PROMPT,
    ENTER_VALID_RESPONSE_PROMPT,
    ENTER_VALID_TEXT_PROMPT,
    ENTER_WPM_PROMPT,
    EXIT_MSG,
    HELP_DESCRIPTION,
    MODIFIED_TEXT_COPIED_MSG,
    REGEX_NOT_FOUND_MSG,
    TEXT_NOT_FOUND_MSG
)

__all__ = [
    'ANY_OTHER_TEXT_PROMPT',
    'CASE_NOT_FOUND_MSG',
    'CLIPBOARD_ACCESS_ERROR_MSG',
    'CLIPBOARD_CLEARED_MSG',
    'ENTER_CASE_TO_REPLACE_PROMPT',
    'ENTER_MFW_COUNT_PROMPT',
    'ENTER_REGEX_PROMPT',
    'ENTER_REPLACEMENT_CASE_PROMPT',
    'ENTER_REPLACEMENT_TEXT_PROMPT',
    'ENTER_TEXT_TO_REPLACE_PROMPT',
    'ENTER_VALID_CASE_PROMPT',
    'ENTER_VALID_NUMBER_PROMPT',
    'ENTER_VALID_REGEX_PROMPT',
    'ENTER_VALID_RESPONSE_PROMPT',
    'ENTER_VALID_TEXT_PROMPT',
    'ENTER_WPM_PROMPT',
    'EXIT_MSG',
    'HELP_DESCRIPTION',
    'MODIFIED_TEXT_COPIED_MSG',
    'REGEX_NOT_FOUND_MSG',
    'TEXT_NOT_FOUND_MSG',
    'get_exit_inputs',
    'get_no_inputs',
    'get_yes_inputs',
]
