"""Exposes command-line inputs and messages."""

from textwarp._cli.constants.inputs import EXIT_INPUTS, NO_INPUTS, YES_INPUTS
from textwarp._cli.constants.messages import (
    ANY_OTHER_TEXT_PROMPT,
    CASE_NOT_FOUND_MESSAGE,
    CLIPBOARD_ACCESS_ERROR_MESSAGE,
    CLIPBOARD_CLEARED_MESSAGE,
    ENTER_CASE_TO_REPLACE_PROMPT,
    ENTER_MFW_COUNT_PROMPT,
    ENTER_VALID_NUMBER_PROMPT,
    ENTER_REGEX_PROMPT,
    ENTER_REPLACEMENT_CASE_PROMPT,
    ENTER_REPLACEMENT_TEXT_PROMPT,
    ENTER_TEXT_TO_REPLACE_PROMPT,
    ENTER_VALID_CASE_PROMPT,
    ENTER_VALID_REGEX_PROMPT,
    ENTER_VALID_RESPONSE_PROMPT,
    ENTER_VALID_TEXT_PROMPT,
    ENTER_WPM_PROMPT,
    EXIT_MESSAGE,
    HELP_DESCRIPTION,
    MODIFIED_TEXT_COPIED_MESSAGE,
    REGEX_NOT_FOUND_MESSAGE,
    TEXT_NOT_FOUND_MESSAGE
)

__all__ = [
    'EXIT_INPUTS',
    'NO_INPUTS',
    'YES_INPUTS',
    'ANY_OTHER_TEXT_PROMPT',
    'CASE_NOT_FOUND_MESSAGE',
    'CLIPBOARD_ACCESS_ERROR_MESSAGE',
    'CLIPBOARD_CLEARED_MESSAGE',
    'ENTER_CASE_TO_REPLACE_PROMPT',
    'ENTER_MFW_COUNT_PROMPT',
    'ENTER_VALID_NUMBER_PROMPT',
    'ENTER_REGEX_PROMPT',
    'ENTER_REPLACEMENT_CASE_PROMPT',
    'ENTER_REPLACEMENT_TEXT_PROMPT',
    'ENTER_TEXT_TO_REPLACE_PROMPT',
    'ENTER_VALID_CASE_PROMPT',
    'ENTER_VALID_REGEX_PROMPT',
    'ENTER_VALID_RESPONSE_PROMPT',
    'ENTER_VALID_TEXT_PROMPT',
    'ENTER_WPM_PROMPT',
    'EXIT_MESSAGE',
    'HELP_DESCRIPTION',
    'MODIFIED_TEXT_COPIED_MESSAGE',
    'REGEX_NOT_FOUND_MESSAGE',
    'TEXT_NOT_FOUND_MESSAGE'
]
